### PR TITLE
Updating thermarquis to use latest version of scaffold-stark

### PR DESCRIPTION
**Pull request by od-hunter**
# Task name here

Fixes #relevant-issue-here

## Types of change

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

### CODE REVIEW

**Comment by od-hunter** [comment]
Resolves #75 
I’m still working on it.

**Comment by od-hunter** [comment]
GM @gianalarcon , I’ve added more changes/updates, please review although I’m still working on it.

**Comment by Buuh2511** [comment]
i faced on this issue when launch app, fix it plss
Screenshot 2024-11-26 at 1 39 40 PM

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
I see you tried to update Marquis based on Scaffold Stark. This is exactly what we expected, but there are still some shortcomings : 
- Missing test folder [path](/nextjs/app/debug/_components/contract/__test__) & [path](Scaffold-Stark/scaffold-stark-2/packages/nextjs/hooks/scaffold-stark/__tests__)
- Many files [path](/nextjs/components/scaffold-stark) still have not updated)

**Comment by gianalarcon** [comment]
Hi @od-hunter. Any updates on this?

**Comment by od-hunter** [comment]
> Hi @od-hunter. Any updates on this?

Yes made great progress and will push what I have so far shortly 🙏🏻

**Comment by gianalarcon** [comment]
Hi @od-hunter will you still work on this, We expect to close this issue asap. If the PR is not ready on few hours, we will give the chance to another candidate. thanks!

**Pull request closed without merging**
