### PR TITLE
Creating tests for Wallet Interactions functionality issue #79

### PR DESCRIPTION
**Pull request by OlgaKush512**
# Task name here

Creating tests for Wallet Interactions functionality issue #79

### CODE REVIEW

**Comment by gianalarcon** [comment]
Hi @OlgaKush512 , is your PR ready? It should point to develop branch, not to main branch

**Comment by OlgaKush512** [comment]
Hi, I've updated the PR to develop.

**Comment by gianalarcon** [comment]
Hi @OlgaKush512. This PR doesn't cover all the scope that is described on the issue

**Comment by OlgaKush512** [comment]
Hi! Yes, of course, because it is a draft PR. I'm working on this.

**Comment by OlgaKush512** [comment]
Hi @gianalarcon! I just want to give you a heads up. I created a new PR (https://github.com/The-Marquis-Gaming/themarquis-ui-sc/pull/89) with a new branch where I use Vitest instead of Jest. Honestly, I struggled with the Jest configuration all night, and I must say there were issues with internal dependencies.

**Pull request closed without merging**
