### PR TITLE
feat: update wallet and fix logo of website

### LINKED ISSUE #71: UI Web site: Update Wallet and fix logo of website
## Issue Overview

1. Update marquis wallet interface based on new design.
2. When search marquis on "google", it shows a white logo and repetitve domain 'xyz'.
image

### Wallet
- Implement design (new wallet dropdown - first part) [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5274&node-type=section&t=wQYAxVCgHjbwNz9d-0).

### Google search result
- Use this [App-logo.zip](https://github.com/user-attachments/files/17771985/App-logo.zip) to update the logo
- Make sure the favicon work well on dark mode & light mode
- Replace `themarquis.xyz` with `The Marquis`

### PR DESCRIPTION
**Pull request by NueloSE**
# UI Web site: Update Wallet and fix logo of website

Fixes #71 

## Types of change

- [ ] Feature
- [x] Bug
- [x] Enhancement

## Description
- implement the upgrade new UI for marquis wallet and blockchain wallet is done
- fixing google search console have done my research and couldn't find a fix
- kindly review my upgrade implementation and if you avaliable we could jump on a call as regards google search console issue

### CODE REVIEW

**Comment by NueloSE** [comment]
- ATM the UI upgrade has been implemented
- The google search output might be because google is not fully utilizing the metadata we defined, this may be as a result of incomplete configuration, indexing delays, or how Google's algorithm is processing the site. 
- All possible title in the layout.tsx have been update to "The Marquis" but for some reason the google search enginee site renders it as "themarquis.xyz".

**Comment by Buuh2511** [comment]
Any update on this. Should speed up progress

**Comment by Buuh2511** [comment]
Your implement do not the same with Figma
Screenshot 2024-11-26 at 10 47 33 AM
Screenshot 2024-11-26 at 10 48 13 AM

**Comment by Buuh2511** [comment]
Can not connect wallet here
Screenshot 2024-11-26 at 10 49 36 AM

**Comment by Buuh2511** [comment]
The spacing does not match Figma

Screenshot 2024-11-26 at 10 51 59 AM

**Comment by NueloSE** [comment]
Currently have fixed the my implementation to match the design 

Can we have a meet I need clarification on "cannot connect wallet" u mention above

**Comment by Buuh2511** [comment]
Thanks for your contributions @NueloSE

**Pull request closed without merging**
