### PR TITLE
feat: update wallet and fix logo of website

### LINKED ISSUE #71: UI Web site: Update Wallet and fix logo of website
## Issue Overview

1. Update marquis wallet interface based on new design.
2. When search marquis on "google", it shows a white logo and repetitve domain 'xyz'.
image

### Wallet
- Implement design (new wallet dropdown - first part) [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5274&node-type=section&t=wQYAxVCgHjbwNz9d-0).

### Google search result
- Use this [App-logo.zip](https://github.com/user-attachments/files/17771985/App-logo.zip) to update the logo
- Make sure the favicon work well on dark mode & light mode
- Replace `themarquis.xyz` with `The Marquis`

### PR DESCRIPTION
**Pull request by NueloSE**
# UI Web site: Update Wallet and fix logo of website 

Fixes #71 

## Types of change

- [x] Feature
- [ ] Bug
- [ ] Enhancement

## Comments
yet to Replace `themarquis.xyz` with `The Marquis`

### CODE REVIEW

**Comment by NueloSE** [comment]
@Buuh2511 @gianalarcon this PR is ready for review

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
Hi @NueloSE, make sure u are understanding what u have to do, if u have any question, leave your comment plss. I am happy to answer. 

1. I wanna let u know this is our production have deployed on V1 and its working verry well, but still missed some issue from Google Search Console
2. Your task are : 
  upgrade new UI for : 
    + Marquis Wallet
    + BlockChain Wallet (Argenxt, Braavos)
  fix issue relevant Google search console

Finnaly, make sure every functional are still working well. Do not change anythings relative to another your task like: Docker file, GamesCarousel.tsx, ...

Your updated commit still not match Figma
Button connect wallet should be open wallet connector

**Comment by gianalarcon** [comment]
At the same time, remember that your PR should point to `develop` branch, not `main` branch. 
As it was mentioned on the issue 
https://github.com/The-Marquis-Gaming/themarquis-ui-sc/issues/71#issuecomment-2491776264

**Comment by Buuh2511** [comment]
kindly reminding, if u need anything else to complete your task, leave your comment @NueloSE 
this change should be Enhancement & Bug

**Pull request closed without merging**
