### PR TITLE
Environment setup for Vittest in Next + deposit tests input

### PR DESCRIPTION
**Pull request by OlgaKush512**

### CODE REVIEW

**Comment by Buuh2511** [comment]
Why u drop 2 PR for 1 issue ? Should be one plse

**Comment by OlgaKush512** [comment]
Hi @Buuh2511 ! It will be this PR!

**Comment by Buuh2511** [comment]
hi @OlgaKush512, is this PR ready for check ?

**Comment by OlgaKush512** [comment]
Hi @Buuh2511 , yes, you can review it.

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- In general, current tests focus mainly on:
  - Input validation
  - Basic UI state
  - Basic transaction flow
  - Information display
  - Balance check
  
- Missing cases:
  - Test Cases for Deposit Function:
    - Loading states:
        1. loading indicator while processing transaction
        2. loading state while fetching balance
        3. disable UI elements while loading
    -  Cancel Transaction:
        1. cancel transaction
        2. UI state after cancel
        3.  cleanup after cancel
    - Error Handling:
        1. network errors
   - Test Cases for Withdraw Function:
      - Network Errors:
        1. network error handling
        2. error notification
      - Transaction States:
        1. Pending state
        2. Failed state
        3. transition state

**Comment by OlgaKush512** [comment]
Hi @Buuh2511! Oki I'll do it!

**Comment by OlgaKush512** [comment]
Hi @Buuh2511 !
I have a question about this case:

Test Cases for Deposit Function:
Loading States:
-------> Loading state while fetching balance
There is no loading indicator on the page when the balance is being fetched. Could you please explain this functionality in more detail?

**Comment by Buuh2511** [comment]
For example : 
- I have 10 strk on Marquis wallet. After deposit 1 strk from ArgentX wallet to Marquis wallet, in successfully case should be loading from 10 to 11
- Can check this [hook](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/main/packages/nextjs/hooks/scaffold-stark/useScaffoldStrkBalance.ts) to check loading state while fetch balance

**Comment by OlgaKush512** [comment]
@Buuh2511 
And for 2nd question? 
---->where is the functionality for canceling the transaction defined?

**Comment by Buuh2511** [comment]
> @Buuh2511 And for 2nd question? ---->where is the functionality for canceling the transaction defined?

user click reject/cancel on wallet -> throw error
Check this [function ](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/ab9b65520deedadef766617ead2a1a97c462f084/packages/nextjs/app/deposit/page.tsx#L61-L89) and [hook ](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/main/packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts)to cover case cancel transaction. Focus on "catch"

**Comment by OlgaKush512** [comment]
Hi @Buuh2511 ! 
I'm trying to figure out the notifications in Withdrawal, and I realized that the error notification never appears because `fetchPriceFromCoingecko` never throws an exception; it only logs errors with console.error.

**Comment by OlgaKush512** [comment]
@Buuh2511,  

I wanted to let you know that for the test cases:  
Transaction States:  
- Pending state  
- Failed state  
- Transition state  

I have only added the Pending state for now, as all other cases were already tested earlier in the file `WithdrawalTransaction.test.tsx`.

You can review it.

**Comment by Buuh2511** [comment]
> Hi @Buuh2511 ! I'm trying to figure out the notifications in Withdrawal, and I realized that the error notification never appears because `fetchPriceFromCoingecko` never throws an exception; it only logs errors with `console.error`.

I checked and it is true that the [function ](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/main/packages/nextjs/app/withdrawal/page.tsx#L86-L104)does not throw an exception case
many thanks for your remind
you can ignore this case

**Comment by Buuh2511** [comment]
Hi @OlgaKush512, here is my review for your contributions, feel free to leave your comment if i missed anything and make this test suite more complete and maintainable in the future

- Deposit Function Coverage
  ✅UI Elements  
  ✅User Interactions  
  ✅Integration 
  
- Withdraw Function Coverage
  ✅UI Elements  
  ✅User Flows  
  ✅Transaction States 
  
-  Core Test Points Coverage
    ✅ Component rendering
    ✅ User interactions
    ✅ Error handling
    ✅ Loading states
    ✅ Form validation
    ✅ Transaction flow
    ✅ Event handling
    **=>All points covered**
    

-  Conclusion:
  The current test suite has achieved all the requirements. Each part of the requirement has at least one corresponding test case, and many cases have multiple detailed test cases. The test coverage is quite comprehensive from UI elements to business logic
- Particular strengths are:
  Very detailed test cases for input validation
  Good coverage for edge cases
  Full handling of loading and error states
  Good mocking of network interactions

**Review by Buuh2511 — APPROVED** [review]

**Pull request merged**
