### PR TITLE
Implement responsive brandkit

### LINKED ISSUE #78: Implement responsive Brandkit page & Loading component
## Issue Overview
- [ ] 1. Upgrade PC version to new Figma
- [ ] 2. Implement responsive Brandkit UI page [here](https://www.figma.com/design/Ybq9WIO2OrdTHH21yH1Ty9/The-Marquis-Brandkit-(Only-Dust)?node-id=1-179&node-type=frame&t=iV1O7UXzoIfHGNA9-0) via : /brandkit
- [ ] 3. Implement a loading when redirect to another page

## Proposed Solutions or Ideas
- Add suspend loading page (need to check prototype) , [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3512-8180&node-type=frame&t=wQYAxVCgHjbwNz9d-0)
- Add [this part](https://www.figma.com/design/Ybq9WIO2OrdTHH21yH1Ty9/The-Marquis-Brandkit-(Only-Dust)?node-id=1-46&node-type=frame&t=sP4YLXyPeKn04aHz-0) to Color section 

## Final result
Expect correctly a hundred percent for version width : 390px & PC version
Resonpisve should work well on every screen
Loading components must be preloaded whenever needed

## Note
Drop PR base on develop branch
Implementation time is 24 hours from assignment

### PR DESCRIPTION
**Pull request by Michaelkingsdev**
# Implement Responsive Brandkit Page

Fixes #78 

## Types of change

- [ ] Feature
- [ ] Bug
- [x] Enhancement

# Before
[Watch Before Here](https://www.webmobilefirst.com/en/screencasts/aqm347fgsu9fvu/)

# After
[Watch After Here](https://www.webmobilefirst.com/en/screencasts/hqlcosi7040yl8/)

### CODE REVIEW

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- Hi, although we do not provide table screen but it should work well on every screen size & for the correctly version width - 390px, its should be matched a hundred percent with Figma
- Adjust your PR base on this pls : 
  1. align space between sections
  2. mapping font size for mobile screen
  3. add Accent part on Color section, could u plse do aslo for PC version ? [link here](https://www.figma.com/design/Ybq9WIO2OrdTHH21yH1Ty9/The-Marquis-Brandkit-(Only-Dust)?node-id=1-179&node-type=frame&t=lJiALsrH4RG1EDDW-0)
- Finnaly, run yarn format before your commit

**Comment by Michaelkingsdev** [comment]
> * Hi, although we do not provide Tablet or Ipad screen but it should work well on every screen size & for the correctly version width - 390px, its should be matched a hundred percent with Figma
> * Adjust your PR base on this pls :
>   
>   1. align space between sections
>   2. mapping font size for mobile screen
>   3. add Accent part on Color section, could u plse do aslo for PC version ? [link here](https://www.figma.com/design/Ybq9WIO2OrdTHH21yH1Ty9/The-Marquis-Brandkit-(Only-Dust)?node-id=1-179&node-type=frame&t=lJiALsrH4RG1EDDW-0)
> * Finnaly, run yarn format before your commit

Alright sir

**Comment by gianalarcon** [comment]
Hi @Michaelkingsdev. Checking in on your progress. Please fix your PR within the next few hours. Let me know if you're blocked.

**Comment by Michaelkingsdev** [comment]
> Hi @Michaelkingsdev. Checking in on your progress. Please fix your PR within the next few hours. Let me know if you're blocked.

Alright sir

**Comment by Michaelkingsdev** [comment]
I will update my PR soon

**Comment by Buuh2511** [comment]
Thanks for your contribution

**Comment by Buuh2511** [comment]
Thanks for your contribution

**Pull request closed without merging**
