### PR TITLE
Refactor UI website fix

### LINKED ISSUE #74: UI Web site: Fix Landing page and Fix Mobile responsive (Banner, sign-in/sign-up)
### Landing Page

- Update Landing Page to match with provided design, pay attention to the details [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5273&node-type=section&t=VbsLmNRi97qWmyNZ-0)

### Login/Signup Page
- Implement UI match with new Figma [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5273&node-type=section&t=Ml3tHeDpoLpDEWyZ-0)

### Responsive
- Implement responsive Login/Signup page for Mobile [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3193-2257&node-type=section&t=VbsLmNRi97qWmyNZ-0)
- Implement responsive Login/Signup page for Tablet [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-8640&node-type=section&t=VbsLmNRi97qWmyNZ-0)
- Implement responsive Twitter invite post [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3158-5373&node-type=section&t=VbsLmNRi97qWmyNZ-0)

### Landing Page
- Fix based on provided design. Google play and app store logos
- Fix carousel : match size for active slide & inactive slide, make sure mobile version work well
- Fix align space between sections
- Fix effect at "Sign up now" button

### Login/Signup Page
- Fix based on new background

### Mobile responsive
- Fix based on provided design

### PR DESCRIPTION
**Pull request by josephchimebuka**
#74 

Fixes #74 
Fixed landing page UI and responsiveness too

### CODE REVIEW

**Comment by gianalarcon** [comment]
Hi @josephchimebuka . Remember that your PR should point to `develop` branch, not `main` branch.
As it was mentioned on the issue description 
https://github.com/The-Marquis-Gaming/themarquis-ui-sc/issues/74#issuecomment-2493112041

**Comment by josephchimebuka** [comment]
@gianalarcon done it ser

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
Do i missing some thing ?
 I just see your commit changed a little bit relevant UI at 
   - packages/nextjs/components/Landingpage/DownloadMarquis.tsx
   - packages/nextjs/components/Landingpage/MarquisMobile.tsx
   - packages/nextjs/components/Landingpage/SignupSection.tsx
   - packages/nextjs/components/Landingpage/style.css
I have listed a lots of task u need to do #74, check it carefully
Make sure u know what u must do on that, otherwise just leave your comment

**Comment by gianalarcon** [comment]
Hi @josephchimebuka. Checking in on your progress. Please fix your PR within the next few hours. Let me know if you're blocked.

**Comment by josephchimebuka** [comment]
Hello @Buuh2511 pls what is your handle on discord there is something I want to ask

**Comment by Buuh2511** [comment]
> Hello @Buuh2511 pls what is your handle on discord there is something I want to ask

Leave your question [here ](https://discord.com/channels/1297763340868915260/1309810346894295121) pls

**Comment by Buuh2511** [comment]
u have to pay attention to even the smallest details.
we have many changes on Figima compare to current version. u need to fix current version according to new Figma
- fix alignment
- fix game slider
 for example
its should be matched a hundred percent to Figma for PC version & Mobile version

your current update cannot be considered as a result of the development process being completed. Should check your result before drop a PR
everthing not working as i expected, fix it plss

u have too many bugs on the UI, just for example : 
image
image
image
image

**Comment by gianalarcon** [comment]
Thanks for your contribution @josephchimebuka . We close this PR for now

**Comment by josephchimebuka** [comment]
Hello @Buuh2511 I was not done I just wanted u to see I was making progress I had not touched the swiper for mobile view just completed it now... But thanks for the opportunity

> u have to pay attention to even the smallest details. we have many changes on Figima compare to current version. u need to fix current version according to new Figma, for example :
> 
> * fix alignment
> * fix game slider
> 
> its should be matched a hundred percent to Figma for PC version & Mobile version
> 
> your current update cannot be considered as a result of the development process being completed. Should check your result before drop a PR everthing not working as i expected, fix it plss
> 
> u have too many bugs on the UI, just for example : image image image image

**Pull request closed without merging**
